apps/producto/urls.py
from django.urls import path

from . import views
from .views import (
    CategoriaDelete,
    CategoriaEditar,
    CategoriaNew,
    CategoriaView,
    MarcaDelete,
    MarcaEditar,
    MarcaNew,
    MarcaView,
    ProductoDelete,
    ProductoEditar,
    ProductoNew,
    ProductoView,
    TipoProductoDelete,
    TipoProductoEditar,
    TipoProductoNew,
    TipoProductoView,
    delete_cart_shopping,
    deletetodocarrito,
    deletetodoCategoria,
    deletetodoMarca,
    deletetodoProducto,
    deletetodoTipoProducto,
    update_carrito,
    ListCarritoView,
)

# Le asignamos un nombre a la app
app_name = "prod"

urlpatterns = [
    # Urls Marca
    path("marca/list", MarcaView.as_view(), name="marca_list"),
    path("marca/new", MarcaNew.as_view(), name="marca_new"),
    path("marca/edit/<int:pk>", MarcaEditar.as_view(), name="marca_edit"),
    path("marca/Delete/<int:pk>", MarcaDelete.as_view(), name="marca_Delete"),
    path("deleallmarca", deletetodoMarca.as_view(), name="deletetodomarca"),
    # Urls Categorias
    path("categorias/list", CategoriaView.as_view(), name="categoria_list"),
    path("categorias/new", CategoriaNew.as_view(), name="categoria_new"),
    path("categorias/edit/<int:pk>", CategoriaEditar.as_view(), name="categoria_edit"),
    path("categorias/Delete/<int:pk>", CategoriaDelete.as_view(), name="categoria_Delete"),
    path("deleteallcategoria", deletetodoCategoria.as_view(), name="deletetodocategoria"),
    # Urls Tipo de Producto
    path("TipoProducto/list", TipoProductoView.as_view(), name="tipoproducto_list"),
    path("TipoProducto/new", TipoProductoNew.as_view(), name="tipoproducto_new"),
    path("TipoProducto/edit/<int:pk>", TipoProductoEditar.as_view(),name="tipoproducto_edit",),
    path("TipoProducto/Delete/<int:pk>", TipoProductoDelete.as_view(), name="TipoProducto_delete", ),
    path("delealltipoproducto", deletetodoTipoProducto.as_view(), name="deletetodotipoproducto",
    ),
    # Urls Productos.
    path("Producto/list", ProductoView.as_view(), name="producto_list"),
    path("Producto/new", ProductoNew.as_view(), name="producto_new"),
    path("Producto/edit/<str:pk>", ProductoEditar.as_view(), name="Producto_edit"),
    path("Producto/Delete/<str:pk>", ProductoDelete.as_view(), name="Producto_delete"),
    path("Productodeletetodo", deletetodoProducto.as_view(), name="productodeletetodo"),
    # Urls Carrito
    path("update/<str:pk>/", update_carrito, name="updatecarrito"),
    path("añadircarrito/<str:idproducto>/", views.añadircarrito, name="carrito"),
    path("detallecarrito/<str:pk>/", ListCarritoView.as_view(), name="detallecarrito"),
    path("removercarrito/<str:pk>/", delete_cart_shopping, name="removercarrito"),
    path("deleteall/", deletetodocarrito.as_view(), name="deleteall"),
]

ferreteria/urls.py
from apps.users.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin    
from django.urls import include, path
from django.views.generic import TemplateView
from ferreteria.views import DetailViewProducto, ListaCategorias, ListarCategorias

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("apps.dashboard.urls")),
    path("home/abastecimiento/", include("apps.abastecimiento.urls")),

    path("accounts/", include("allauth.urls")),
    path("prod/", include("apps.producto.urls")),
    path("user/", include("apps.users.urls")),
    path("cmp/", include("apps.cmp.urls")),

    path("redireccion/", TemplateView.as_view(template_name="redireccion.html"), name="redirect"),

    path("", ListaCategorias.as_view(), name="inicio"),
    path("ListarCategoria/edit/<str:pk>", ListarCategorias.as_view(), name="Listar_categorias"),
    path("Detalleproducto/<str:pk>", DetailViewProducto.as_view(), name="Detalle_Producto"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/cmp/models.py
from apps.bases.models import ClaseModelo
from apps.producto.models import Carrito, CarritoProducto, Categoria, Producto
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

""" class Venta(ClaseModelo):
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    id_venta
    Total
    Id_tipo_Usuario
    Comuna
    Direccion
    Rut
    proveedor=models.ForeignKey(settings.AUTH_USER_MODEL ,on_delete=models.CASCADE,limit_choices_to={'cargo':'Proveedor'}) """


class venta(ClaseModelo):
    LISTA_TIPOS_DOCUMENTOS = (
        ('BOLETA', 'Boleta'),
        ('FACTURA', 'Factura'),
    )
    LISTA_TIPOS_DESPACHO = (
        ('DOMICILIO', 'Domicilio'),
        ('TIENDA', 'Recojo en tienda'),
    )
    LISTA_ESTADOS = (
        ('BORRADOR', 'BORRADOR'),
        ('PENDIENTE', 'Pendiente'),
        ('PAGADO', 'Pagado'),
    )
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, null=True)
    direccion = models.CharField('Dirección', max_length=250, blank=True, null=True, help_text="direccion")
    ciudad = models.CharField('Ciudad', max_length=100, blank=True, null=True)
    comuna = models.CharField('Comuna', max_length=100, blank=True, null=True, help_text="comuna")
    tipo_documento = models.CharField('Tipo documento', max_length=15, null=True, blank=False, default='BOLETA',
                                      choices=LISTA_TIPOS_DOCUMENTOS)
    tipo_despacho = models.CharField('Estado', max_length=15, null=True, blank=False, default='TIENDA',
                                     choices=LISTA_TIPOS_DESPACHO)
    cli_nombres = models.CharField('Nombres', max_length=250, blank=True, null=True)
    cli_apellidos = models.CharField('Apellidos', max_length=250, blank=True, null=True)
    cli_rut = models.CharField('Rut', max_length=250, blank=True, null=True)
    cli_empresa = models.CharField('Empresa', max_length=250, blank=True, null=True)
    precio = models.IntegerField('Precio', blank=False, default=0)  # costo total de la venta
    estado = models.CharField('Estado', max_length=30, blank=False, default='BORRADOR', choices=LISTA_ESTADOS)

    def __str__(self):
        return "{}".format(self.id)

    def actualiza_stock(self):
        for item in self.carrito.detalles.all():
            item.producto.actualizarStock(item.cantidad*-1)
            item.producto.save()

apps/producto/models.py
from apps.bases.models import ClaseModelo
from apps.users.models import User

# from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
import json
import requests
 
# Creamos la clase categoria
class Categoria(ClaseModelo):
    Nombre = models.CharField(
        max_length=50, help_text="Nombre de la categoria", unique=True
    )

    def __str__(self):
        return "{}".format(self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"


class TipoProducto(ClaseModelo):
    UNIT_CHOICES = (
        ("Kgs", "Kilogramos"),
        ("Lts", "Litros"),
        ("Un", "Unidades"),
    )
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    Nombre = models.CharField(max_length=50, help_text="Nombre de la categoria")
    Um = models.CharField("unidad de medida", max_length=15, choices=UNIT_CHOICES,)

    def __str__(self):
        return "{}:{}".format(self.categoria.Nombre, self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(TipoProducto, self).save()

    class Meta:
        verbose_name_plural = "Tipos de Productos"
        unique_together = ("categoria", "Nombre")


class Marca(ClaseModelo):
    """
    Marca de un Producto 
    """

    nombre = models.CharField("Nombre", max_length=30, default="Marca")

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"

    def __str__(self):
        return self.nombre


class Producto(ClaseModelo):
    Nombre = models.CharField(max_length=40, blank=False, help_text="Nombre de producto" )
    codigo = models.CharField(primary_key=True, max_length=18)
    precio = models.FloatField(default=0)
    descripcion = models.CharField(max_length=100, help_text="Descripcion de productos", default="descripcion")
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    color = models.CharField(max_length=20, help_text="Color del producto", null=True, blank=True)
    stock = models.IntegerField()
    id_proveedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                     limit_choices_to={"cargo": "Proveedor"}, )
    imagen = models.ImageField(upload_to="ferreteria",  null=True, blank=True)
    Categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    TipoProducto = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def actualizarStock(self, cantidad):
        # 10 => compro 5 ==> enviar (-5)
        # x = 10 + (-5) => 5
        if cantidad:
            try:
                self.stock += int(cantidad)
                self.save()
            except Exception as e:
                print("Error : {}".format(str(e)))

    def limit_stock(self):
        item=self.stock
        item=int(item)
        if (item <= 25):
            return 1
        if (item <= 60):
            return 2
        if (item >= 61 ):   
            return 3


class Carrito(models.Model):

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    ESTATUS = [
        ("open", "Abierto"),
        ("pagado", "Pagado"),
        ("pendiente", "Pendiente"),
    ]
    estatus = models.CharField(max_length=59, choices=ESTATUS, default="open",)
    monto_total = models.FloatField('Monto total', default=0)

    def get_total(self):
        total = 0
        for carrito_producto in self.detalles.all():
            total += carrito_producto.producto.precio * carrito_producto.cantidad
        return total

    def __str__(self):
        return "{}".format(self.id)


class CarritoProducto(models.Model):
    carrito = models.ForeignKey(
        Carrito, on_delete=models.CASCADE, related_name="detalles"
    )
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)

    def get_precio_parcial(self):
        return self.cantidad * self.producto.precio

    def __str__(self):
        return "{}".format(self.id)

apps/producto/forms.py
from django import forms

# Importamos el modelo al cual queremos acceder.
from .models import Categoria, Marca, Producto, TipoProducto, Carrito
# Realizamos el formularios de las categorias ...
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ["Nombre"]  # Que quieres que se muestre
        labels = {"nombre": "Nombre de la categoria"}
        widget = {"Nombre": forms.TextInput}  # Darle estilo

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
    
    #Validacion del Nombre
    # def clean_Nombre(self):
    #     Nombre= self.cleaned_data['Nombre']
    #     if not Nombre.isalpha():
    #         print('Nombre',Nombre)
    #         raise forms.ValidationError("No se puede ingresar un tipo de valor Numerico")
    #     return Nombre


# Definimos El forms De tipo de Producto
class TipoProductoForm(forms.ModelForm):
    class Meta:
        model = TipoProducto
        fields = ["categoria", "Nombre", "Um"]
        labels = {"nombre": "Nombre de producto"}
        widget = {"Nombre": forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
        self.fields["categoria"].empty_label = "Seleccione Categoria"
        self.fields["Nombre"].widget.attrs.update(
            {"placeholder": " Nombre del tipo de Producto"}
        )
        self.fields["Um"].widget.attrs.update(
            {"placeholder": " Ingrese Unidad de medida"}
        )

    #Validacion de categoria
    def clean_categoria(self):
        categoria =self.cleaned_data['categoria']
        if categoria == '':
            raise forms.ValidationError("No puede estar el campo Vacio")
        return categoria

    # def clean_Nombre(self):
    #     Nombre =self.cleaned_data['Nombre']
    #     if not Nombre.isalpha():
    #         print('Nombre',Nombre)
    #         raise forms.ValidationError("No se puede ingresar un tipo de valor Numerico")
    #     return Nombre
#Validamos el tipo de producto



# Definimos El forms de producto


class ProductoForms(forms.ModelForm):
    class Meta:
        model = Producto  # Seleccionamos el producto en el cual queremos acceder
        fields = [
            "Nombre",
            "codigo",
            "precio",
            "descripcion",
            "marca",
            "color",
            "stock",
            "id_proveedor",
            "imagen",
            "Categoria",
            "TipoProducto",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
            self.fields["Nombre"].widget.attrs.update(
                {"placeholder": " Nombre del Producto"}
            )
            self.fields["codigo"].widget.attrs.update(
                {"placeholder": " Ingrese codigo"}
            )
            self.fields["stock"].widget.attrs.update({"placeholder": " Stock"})
            self.fields["descripcion"].widget.attrs.update(
                {"placeholder": " Descripcion"}
            )
            self.fields["color"].widget.attrs.update({"placeholder": "Ingrese color"})
            self.fields["imagen"].widget.attrs.update({"id": "ImagenTxt"})

# #Validacion de codigo
#     def clean_codigo(self):
#             codigo =self.cleaned_data['codigo']
#             if codigo <= 0:
#                 raise forms.ValidationError("No puede ingresar un valor igual o inferior a 0")
#                 return codigo
#             else:
#                 return codigo
      
#Validacion del stock
    def clean_stock(self):
        stock =self.cleaned_data['stock']
        if stock <= 0:
            raise forms.ValidationError("No puede ingresar un valor igual o inferior a 0")
            return stock
        else:
            return stock

#Validacion del precio
    def clean_precio(self):
        precio =self.cleaned_data['precio']
        if precio <= 0 or precio == "":
            raise forms.ValidationError("No puede ingresar un valor igual o inferior a 0")
            return precio
        else:
            return precio

#Validacion de Nombre 
    # def clean_Nombre(self):
    #     Nombre =self.cleaned_data['Nombre']
    #     if not Nombre.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un dato de valor Numerico")
    #     return Nombre

#Validacion de color
    # def clean_color(self):
    #     color=self.cleaned_data['color']
    #     if not color.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un dato de valor Numerico")
    #     return color
    
#Validacion de descripcion
    # def clean_descripcion(self):
    #     descripcion=self.cleaned_data['descripcion']
    #     if not descripcion.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un dato de valor Numerico")
    #     return descripcion


# Realizamos el formulario de Marca
class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ["nombre"]  # Que quieres que se muestre
        labels = {"nombre": "Nombre de la Marca"}
        widget = {"nombre": forms.TextInput}  # Darle estilo

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
            
    # def clean_nombre(self):
    #     nombre= self.cleaned_data['nombre']
    #     if not nombre.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un tipo de valor Numerico")
    #     return nombre
    
    




class CarritoPagarForm(forms.ModelForm):

    sede_desc = forms.CharField(widget=forms.TextInput(), required=False)

    class Meta:
        model = Carrito
        exclude = ['usuario', 'estatus', 'monto_total']

templates/MostrarProductos/Carrito.html
{% extends "base.html" %}
{% load static %}
{% block titulo %} Detalle carrito {% endblock titulo %}
{% block cuerpo %}

    {% include 'includes/header.html' %}
    {% include 'base/partial/div_errores_presentados_en_formulario.html' %}


    <div class="container">
        <h1 style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
            Carrito de compras
        </h1>
        <table class="table table-dark mt-3 container">
            <thead>
            <tr>
                <th scope="col">Usuario</th>
                <th scope="col">Imagen</th>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Cantidad</th>
                <th>Total</th>
                <th scope="col">Acciones</th>
            </tr>
            </thead>
            <tbody>
            {% for det in carrito.detalles.all %}
                <tr>
                    <td>{{ request.user }}</td>
                    <td>
                        {% if det.producto.imagen %}
                            <img src="{{ det.producto.imagen.url|default_if_none:'' }}" width="50" height="50" alt="">
                        {% else %}
                            <img src="{% static 'img/1.png' %}" class="imagen-responsive" height="50" alt="Sin imagen">
                        {% endif %}
                    </td>
                    <td>{{ det.producto.Nombre }}</td>
                    <td>{{ det.producto.precio }}</td>
                    <td>{{ det.cantidad }}</td>
                    <td><span class="label label-info text-right">{{ det.get_precio_parcial }}</span></td>
                    <td>
                        <form action="{% url 'prod:removercarrito' det.pk %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="7">
                        <div style="margin-top: 50px;">
                            <h1 class="text-center ">No tienes productos en el carro de compra <i
                                    class="movimiento fas fa-shopping-cart fa-4x container  "
                                    style="color: #D3D3D3;"> </i></h1>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if carrito.detalles.all %}
            <div class="form-row">
                <div class="col-md-3 offset-9">
                    <form action="{% url 'prod:deleteall' %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            <i class="far fa-trash-alt"></i>
                            <span>Limpiar Carrito</span>
                        </button>
                    </form>
                </div>
            </div>
            
            <form class="form" action="" method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-3">
                    <h5><b>Tipo de despacho:</b></h5>
                </div>
                <div class="col-md-4">
                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="despacho_tienda" name="tipo_despacho" class="custom-control-input" value="TIENDA" checked="checked" >
                        <label class="custom-control-label" for="despacho_tienda">Recojo en tienda</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="despacho_domicilio" name="tipo_despacho" class="custom-control-input" value="DOMICILIO">
                        <label class="custom-control-label" for="despacho_domicilio">Despacho a domicilio</label>
                    </div>
                </div>


            </div>
            <hr>
            <h4 >Datos personales</h4>
            <div class="form-row">
                <div class="col-md-3 mb-3">
                    <label for="state">Tipo de documento</label>
                    <select class="custom-select d-block w-100" id="tipo_documento" name="tipo_documento" required>
                        <option value="BOLETA">Boleta</option>
                        <option value="FACTURA">Factura</option>
                    </select>
                    </div>
                <div class="col-md-3 mb-3">
                    <label for="id_cli_rut">Rut</label> <span class="required">*</span>
                    <input type="text" class="form-control" id="id_cli_rut" name="cli_rut" value="{{ user.rut|default_if_none:'' }}" autocomplete="off">
                </div>
                <div class="col-md-3 mb-3">
                    <label for="id_cli_nombres" id="txt_nombres">Nombres</label> <span class="required">*</span>
                    <input type="text" class="form-control" id="id_cli_nombres" name="cli_nombres" value="{{ user.first_name }}" autocomplete="off">
                </div>
                <div class="col-md-3 mb-3" id="datos_apellidos">
                    <label for="id_cli_apellidos">Apellidos</label> <span class="required">*</span>
                    <input type="text" class="form-control" id="id_cli_apellidos" name="cli_apellidos" value="{{ user.last_name }}" autocomplete="off">
                </div>
            </div>
            <div class="form-row" id="div_datos_empresa">
                <div class="col-md-12 mb-3">
                    <label for="id_cli_empresa">Empresa</label> <span class="required">*</span>
                    <input type="text" class="form-control" id="id_cli_empresa" name="cli_empresa" value="" autocomplete="off">
                </div>
            </div>
            <h4 id="titulo_despacho_domicilio">Dirección del despacho</h4>
            <div class="form-row" id="div_datos_despacho">
                <div class="col-md-12 mb-3">
                    <label for="id_direccion">Dirección</label> <span class="required">*</span>
                    <input type="text" class="form-control" id="id_direccion" name="direccion" value="" autocomplete="off">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="id_ciudad">Ciudad</label> <span class="required">*</span>
                    <select id="id_ciudad"  name="ciudad" class="form-control"></select>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="id_comuna">Comuna</label> <span class="required">*</span>
                    <select id="id_comuna" name="comuna" class="form-control"></select>
                </div>
            </div>

            <hr>
                <div class="form-row">
                    <div class="col-md-4 offset-8">
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>$ {{ carrito.get_total }}</strong>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 offset-8">
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Pagar</button>
                    </div>
                </div>
            
            </form>
        {% endif %}

        <div class="clearfix"></div>
    </div>


    
{% endblock cuerpo %}

{% block custom_js %}
    <script src="{% static 'js/detalle_producto.js' %}"></script>
    <script>
        $(document).ready(function() {
            inicializarCampos();
            $("input[name='tipo_despacho']").on("click", function (e) {
                let opcSeleccionada = $(this).val();
                if (opcSeleccionada == 'TIENDA'){
                    ocultarDespachoDomicilio();
                    retirarCamposDespachoRequeridos();
                    $("#id_ciudad").prop("selectedIndex",0);
                    $("#id_comuna").prop("selectedIndex",0);
                }else{
                    mostrarDespachoDomicilio();
                    agregarCamposDespachoRequeridos();
                }
            });

            $("#tipo_documento").on("change", function (e) {
                let opcSeleccionada = $(this).val();
                if (opcSeleccionada == 'FACTURA'){
                    mostrarDatosEmpresa();
                }else{
                    ocultarDatosEmpresa();
                }
            });


        });

        function inicializarCampos() {
            camposRequeridosInicialmente();
            ocultarDespachoDomicilio();
            retirarCamposDespachoRequeridos();
            ocultarDatosEmpresa();
        }

        function camposRequeridosInicialmente() {
            $("#tipo_documento").attr("required", "required");
            $("#id_cli_rut").attr("required", "required");
            $("#id_cli_nombres").attr("required", "required");
            $("#id_cli_apellidos").attr("required", "required");
        }

        function ocultarDespachoDomicilio() {
            $("#titulo_despacho_domicilio").addClass('hide');
            $("#div_datos_despacho").addClass('hide');
        }
        function mostrarDespachoDomicilio() {
            $("#titulo_despacho_domicilio").removeClass('hide');
            $("#div_datos_despacho").removeClass('hide');
        }

        function agregarCamposDespachoRequeridos() {
            $("#id_direccion").attr("required", "required");
            $("#id_ciudad").attr("required", "required");
            $("#id_comuna").attr("required", "required");
        }
        function retirarCamposDespachoRequeridos() {
            $("#id_direccion").removeAttr("required");
            $("#id_ciudad").removeAttr("required");
            $("#id_comuna").removeAttr("required");
        }

        function ocultarDatosEmpresa() {
            $("#div_datos_empresa").addClass('hide');
            $("#datos_apellidos").removeClass('hide');
            $("#id_cli_apellidos").attr("required", "required");
            $("#txt_nombres").html("Nombres");
        }
        function mostrarDatosEmpresa() {
            $("#div_datos_empresa").removeClass('hide');
            $("#datos_apellidos").addClass('hide');
            $("#id_cli_apellidos").removeAttr("required");
            $("#txt_nombres").html("Razon social");
        }

    </script>

{% include 'includes/footer.html' %}
{% endblock %}