apps/abastecimiento/urls.py
from django.urls import path

from . import views

app_name = "abastecimiento"

urlpatterns = [
    path('pedido/list', views.PedidoListView.as_view(), name='pedido_list'),
    path('pedido/add', views.PedidoAddView.as_view(), name='pedido_add'),
    path('pedido/edit/<int:pk>/', views.PedidoEditView.as_view(), name='pedido_edit'),
    path('pedido/delete/<int:pk>/', views.PedidoDeleteView.as_view(), name='pedido_delete'),
    path('pedido/ver/<int:pk>/', views.PedidoShowView.as_view(), name='pedido_detail'),
    path('pedido/list_pendientes', views.PedidoListPendientesView.as_view(), name='pedido_list_pendientes'),
]

ferreteria/urls.py
from apps.users.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin    
from django.urls import include, path
from django.views.generic import TemplateView
from ferreteria.views import DetailViewProducto, ListaCategorias, ListarCategorias

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("apps.dashboard.urls")),
    path("home/abastecimiento/", include("apps.abastecimiento.urls")),

    path("accounts/", include("allauth.urls")),
    path("prod/", include("apps.producto.urls")),
    path("user/", include("apps.users.urls")),
    path("cmp/", include("apps.cmp.urls")),

    path("redireccion/", TemplateView.as_view(template_name="redireccion.html"), name="redirect"),

    path("", ListaCategorias.as_view(), name="inicio"),
    path("ListarCategoria/edit/<str:pk>", ListarCategorias.as_view(), name="Listar_categorias"),
    path("Detalleproducto/<str:pk>", DetailViewProducto.as_view(), name="Detalle_Producto"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/abastecimiento/models.py
from django.db import models
from django.forms import model_to_dict

from apps.producto.models import Producto
from apps.users.models import User


class Pedido(models.Model):
    LISTA_DOCUMENTOS = (
        ('BOLETA', 'Boleta'),
        ('FACTURA', 'Factura'),
    )
    LISTA_TIPOS_PAGO = (
        ('CONTADO', 'Contado'),
        ('CREDITO', 'Credito'),
    )
    LISTA_ESTADOS = (
        ('BORRADOR', 'BORRADOR'),
        ('PENDIENTE', 'Pendiente'),
        ('ACEPTADO', 'Aceptado'),
        ('ENVIADO', 'Enviado'),
        ('RECIBIDO', 'Recibido'),
    )
    numero = models.CharField('Número', max_length=45)
    fecha = models.DateField('Fecha')
    tipo_documento = models.CharField('Tipo documento', max_length=15, blank=False, default='BOLETA',
                                      choices=LISTA_DOCUMENTOS)
    tipo_pago = models.CharField('Tipo pago', max_length=15, blank=False, default='CONTADO',
                                 choices=LISTA_TIPOS_PAGO)
    total = models.FloatField('Total', default=0)
    estado = models.CharField('Estado', max_length=15, blank=False, default='BORRADOR',
                              choices=LISTA_ESTADOS)
    proveedor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pedidos_proveedor')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pedidos_usuario')

    def __str__(self):
        return "{}".format(self.pk)

    class Meta:
        permissions = (
            ('access_modulo_abastecimiento', '* Access modulo abastecimiento'),
            ('list_pedido', 'List pedido'),
        )

    def toJSON(self):
        # muestra todos los campos del modelo con excepcion de los exclude
        item = model_to_dict(self, exclude=[])
        item['fecha'] = self.fecha.strftime("%d/%m/%Y")
        item['proveedor_name'] = self.proveedor.get_full_name()
        item['usuario_name'] = self.usuario.first_name
        return item

    def confirmar_pedido(self):
        self.estado = "PENDIENTE"

    def aceptar_pedido(self):
        self.estado = "ACEPTADO"

    def enviar_pedido(self):
        self.estado = "ENVIADO"

    def recibir_pedido(self):
        self.estado = "RECIBIDO"

    def actualiza_stock(self):
        for item in self.detalles.all():
            item.producto.actualizarStock(item.cantidad)
            item.producto.save()

    def __str__(self):
        return "{}".format(self.usuario.first_name)


class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name='detalles')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='detalles_pedido')
    precio = models.FloatField('precio', default=0)
    cantidad = models.FloatField('cantidad', default=0)
    total = models.FloatField('total', default=0)

    def __str__(self):
        return "{}".format(self.pk)

apps/abastecimiento/forms.py
from django import forms
from django.forms import ModelForm
from apps.abastecimiento.models import Pedido
from apps.producto.models import Producto
from apps.users.models import User


class PedidoForm(ModelForm):
    # campos adicionales del detalle
    producto = forms.ChoiceField(required=False)
    precio = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': '0'}))
    cantidad = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': '0'}))
    subtotal = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': '0'}))

    proveedores = User.objects.filter(cargo="Proveedor").order_by('first_name')
    lista_temp = [('', '-- seleccione --')]
    lista_temp.extend([(x.id, x.first_name) for x in proveedores])

    list_productos = Producto.objects.all().order_by('Nombre')
    lista_temp_productos = [('', '-- seleccione --')]
    lista_temp_productos.extend([(x.pk, '({}) | {}'.format(x.codigo, x.Nombre)) for x in list_productos])

    lista_documentos = [('', '-- seleccione --'), ('FACTURA', 'Factura')]

    class Meta:
        model = Pedido
        exclude = ['estado', 'usuario']
        widgets = {
            'fecha': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off',
            })
        self.fields['numero'].widget.attrs['autofocus'] = True
        self.fields['proveedor'].choices = self.lista_temp
        self.fields['producto'].choices = self.lista_temp_productos
        self.fields['tipo_documento'].choices = self.lista_documentos
        self.fields['total'].widget.attrs['class'] = 'form-control text-right'
        self.fields['total'].widget.attrs['readonly'] = 'readonly'


class PedidoDetailForm(ModelForm):

    class Meta:
        model = Pedido
        exclude = ['estado', 'usuario']
        widgets = {
            'fecha': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off',
                'readonly': 'readonly',
            })

apps/abastecimiento/views.py
from django.contrib import messages
from django.db import transaction
from django.http import JsonResponse
from django.urls import reverse

from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.abastecimiento.forms import PedidoForm, PedidoDetailForm
from apps.abastecimiento.models import Pedido, DetallePedido
from apps.producto.models import Producto


class PedidoListView(ListView):
    template_name = 'abastecimiento/pedido_list.html'
    model = Pedido
    paginate_by = 100

    # se usa el decorador para evitar el crf_token
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        title_page = "Maestro | Pedidos"
        main_title_content = "Pedidos"
        main_subtitle_content = "List"
        subtitle_table = "Lista pedidos"

        context.update({
            'CLASS_MENU_ABASTECIMIENTO': "active",
            'CLASS_SUBMENU_PEDIDOS': "show",
            'CLASS_SUBMENU_PEDIDOS_LIST': "active",
            'title_page': title_page,
            'main_title_content': main_title_content,
            'main_subtitle_content': main_subtitle_content,
            'subtitle_table': subtitle_table,
        })
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Pedido.objects.all():
                    data.append(i.toJSON())
            elif action == 'confirmar':
                id = request.POST['id']
                pedido = Pedido.objects.get(pk=id)
                pedido.confirmar_pedido()
                pedido.save()
            elif action == 'recepcionar':
                id = request.POST['id']
                pedido = Pedido.objects.get(pk=id)
                pedido.recibir_pedido()
                pedido.actualiza_stock()
                pedido.save()
            else:
                data['error'] = "no tiene acciones ejecutadas"
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)


class PedidoAddView(CreateView):
    template_name = 'abastecimiento/pedido_add.html'
    model = Pedido
    form_class = PedidoForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        title_page = "Maestro | Pedidos"
        main_title_content = "Pedidos"
        main_subtitle_content = "Add"
        subtitle_table = "Agregar pedido"

        context.update({
            'CLASS_MENU_ABASTECIMIENTO': "active",
            'CLASS_SUBMENU_PEDIDOS': "show",
            'CLASS_SUBMENU_PEDIDOS_LIST': "active",
            'title_page': title_page,
            'main_title_content': main_title_content,
            'main_subtitle_content': main_subtitle_content,
            'subtitle_table': subtitle_table,
        })
        return context

    def get_success_url(self):
        messages.success(self.request, 'Se registro el ingreso exitoso, {}'.format(self.object.numero))
        return reverse('abastecimiento:pedido_list', kwargs={})

    def form_valid(self, form):
        context = self.get_context_data()
        form = self.form_class(self.request.POST, self.request.FILES)
        try:
            with transaction.atomic():
                if form.is_valid():

                    if not self.request.POST.getlist('producto[]'):
                        msj = 'Debe ingresar productos en el detalle'
                        messages.warning(self.request, msj)
                        return self.form_invalid(form)
                    if not self.request.POST.getlist('cantidad[]'):
                        msj = 'Un problema con las cantidades, favor de revisar'
                        messages.warning(self.request, msj)
                        return self.form_invalid(form)

                    # obtener el usuario logueado
                    usuario = self.request.user

                    # creando el diccionario de item y limpieza
                    lista_productos = self.request.POST.getlist('producto[]')
                    lista_cantidad = self.request.POST.getlist('cantidad[]')
                    lista_precio = self.request.POST.getlist('precio[]')
                    lista_subtotal = self.request.POST.getlist('subtotal[]')
                    list_items = []
                    index = 0
                    for id_producto in lista_productos:
                        if id_producto.isnumeric():
                            list_items.append({
                              'id_producto': id_producto,
                              'cantidad': lista_cantidad[index],
                              'precio': lista_precio[index],
                              'subtotal': lista_subtotal[index],
                            })
                        index += 1
        
                    # guardamos la cabecera
                    form.instance.usuario = usuario
                    form.save()
                    
                    # guardamos detalles
                    self.crear_detalles_pedido(form.instance, list_items)

                    return super().form_valid(form)
                else:
                    return self.form_invalid(form)
        except Exception as e:
            print(e)
            messages.warning(self.request, 'Ocurrió un error vuelva a intentarlo : {}'.format(e))
            return self.form_invalid(form)

    def crear_detalles_pedido(self, obj_pedido,  list_items):
        for item in list_items:
            det = DetallePedido()
            det.pedido = obj_pedido
            det.producto = Producto.objects.get(pk=item['id_producto'])
            det.precio = item['precio']
            det.cantidad = item['cantidad']
            det.total = item['subtotal']
            try:
                det.save()
            except Exception as e:
                print(e)
                mensaje = 'Error al guardar el detalle del pedido | det = {} | Error => {}'.format(str(e), list_items)
                messages.warning(self.request, mensaje)


class PedidoEditView(UpdateView):
    template_name = 'abastecimiento/pedido_add.html'
    model = Pedido
    form_class = PedidoForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        title_page = "Maestro | Pedidos"
        main_title_content = "Pedidos"
        main_subtitle_content = "Add"
        subtitle_table = "Editar pedido"

        context.update({
            'CLASS_MENU_ABASTECIMIENTO': "active",
            'CLASS_SUBMENU_PEDIDOS': "show",
            'CLASS_SUBMENU_PEDIDOS_LIST': "active",
            'title_page': title_page,
            'main_title_content': main_title_content,
            'main_subtitle_content': main_subtitle_content,
            'subtitle_table': subtitle_table
        })
        return context

    def get_success_url(self):
        messages.success(self.request, 'Se actualizo el ingreso, {}'.format(self.object.numero))
        return reverse('abastecimiento:pedido_list', kwargs={})

    def form_valid(self, form):
        context = self.get_context_data()
        # form = self.form_class(self.request.POST, self.request.FILES)
        try:
            with transaction.atomic():
                if form.is_valid():
                    pedido = form.save(commit=False)
                    if not self.request.POST.getlist('producto[]'):
                        msj = 'Debe ingresar productos en el detalle'
                        messages.warning(self.request, msj)
                        return self.form_invalid(form)
                    if not self.request.POST.getlist('cantidad[]'):
                        msj = 'Un problema con las cantidades, favor de revisar'
                        messages.warning(self.request, msj)
                        return self.form_invalid(form)

                    # creando el diccionario de item y limpieza
                    lista_items_eliminar = self.request.POST.getlist('eliminar_item[]')
                    lista_detalle_id = self.request.POST.getlist('detalle_id[]')
                    lista_productos = self.request.POST.getlist('producto[]')
                    lista_cantidad = self.request.POST.getlist('cantidad[]')
                    lista_precio = self.request.POST.getlist('precio[]')
                    lista_subtotal = self.request.POST.getlist('subtotal[]')
                    list_items = []
                    index = 0
                    for id_producto in lista_productos:
                        if id_producto.isnumeric():
                            list_items.append({
                              'id_detalle': lista_detalle_id[index],
                              'id_producto': id_producto,
                              'cantidad': lista_cantidad[index],
                              'precio': lista_precio[index],
                              'subtotal': lista_subtotal[index],
                            })
                        index += 1

                    # guardamos detalles
                    self.crear_detalles_pedido(self.object, list_items)

                    # eliminar items
                    self.eliminar_items(lista_items_eliminar)

                    return super().form_valid(form)
                else:
                    return self.form_invalid(form)
        except Exception as e:
            print(e)
            messages.warning(self.request, 'Ocurrió un error vuelva a intentarlo : {}'.format(e))
            return self.form_invalid(form)

    def crear_detalles_pedido(self, obj_pedido,  list_items):
        for item in list_items:
            if item['id_detalle']:

templates/abastecimiento/pedido_list.html
    {% extends 'base/base_backend.html' %}
{% load i18n %}
{% load static %}
{% load socialaccount %}
{% load widget_tweaks %}

{% block title %}
    {{ title_page }}
{% endblock title %}

{% block links_css_by_page %}
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block links_js_by_page %}
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
{% endblock %}

{% block body %}

    <!-- Page Heading -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between"></div>
    <h1 class="h3 mb-2 text-gray-800">{{ main_title_content }}</h1>
    <div class="row">

        <div class="col-4">
            <a class="btn btn-primary" href="{% url 'abastecimiento:pedido_add' %}"><i class="fas fa-plus"></i>Agregar</a>
        </div>
    </div>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header">
            <h2>{{ subtitle_table }}</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
            <table id="myTableList" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Número</th>
                    <th>Tipo</th>
                    <th>Fecha</th>
                    <th>Proveedor</th>
                    <th>Usuario</th>
                    <th>Tipo de pago</th>
                    <th>Total</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_page %}
    <script>
    $(function () {
        $("#myTableList").DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "destroy": true,
            "responsive": true,
            "autoWidth": false,
            "deferRender": true,
            "ajax": {
                url: window.location.pathname,
                type: 'POST',
                data: {
                    'action': 'searchdata'
                },
                dataSrc: ""
            },
            "columns": [
                { "data": "id" },
                { "data": "numero" },
                { "data": "tipo_documento" },
                { "data": "fecha" },
                { "data": "proveedor_name" },
                { "data": "usuario_name" },
                { "data": "tipo_pago" },
                { "data": "total" },
                { "data": "estado" },
                { "data": "estado" }
            ],
            "columnDefs": [
                {
                    "targets": [-1],  //ultima fila coloca los iconos
                    "class": "text-center",
                    "orderable": false,
                    render: function (data, type, row) {
                        var buttons ='';
                        if (row.estado == 'BORRADOR'){
                            buttons += `<a href="/home/abastecimiento/pedido/edit/` + row.id +`/" class="btn btn-outline-dark btn-sm" title="Editar"><i class="fa fa-edit"></i></a> `;
                            buttons += `<a href="/home/abastecimiento/pedido/delete/` + row.id +`/" class="btn btn-outline-dark btn-sm" title="Eliminar"><i class="fa fa-trash"></i></a> `;
                            buttons += `<a href="#" rel="confirmar" data-codigo="` + row.id + `" class="btn btn-outline-dark btn-sm" title="Confirmar"><i class="fa fa-check"></i></a> `;
                        }else if (row.estado == 'ENVIADO'){
                            buttons += `<a href="#" rel="recepcionar" data-codigo="` + row.id + `" class="btn btn-outline-dark btn-sm" title="Recepcionar"><i class="fa fa-box-open"></i></a> `;
                        }
                        buttons += `<a href="/home/abastecimiento/pedido/ver/` + row.id +`/" class="btn btn-outline-dark btn-sm" title="Ver detalle"><i class="fa fa-eye"></i></a> `;

                        return buttons
                    }
                }
            ],
            "initComplete": function (settings, json) {
                // alert("tabla cargada");
            }

        });

        $('#myTableList tbody')
        .on('click', 'a[rel="confirmar"]', function () {
            let id= $(this).data("codigo");
            console.log(id);
            Swal.fire({
              title: 'Desea confirmar el pedido ' + id +' ?',
              text: "Se enviara el pedido al proveedor",
              icon: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#c2c2c2',
              confirmButtonText: 'Si, Confirmar!'
            }).then((result) => {
              if (result.value) {
                accionAjaxPedido(id, 'confirmar', 'enviado');
              }
            })
        })
        .on('click', 'a[rel="recepcionar"]', function () {
            let id= $(this).data("codigo");
            Swal.fire({
              title: 'Desea recepcionar el pedido ' + id +' ?',
              text: "Se recepcionara el pedido",
              icon: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#c2c2c2',
              confirmButtonText: 'Si, recepcionar!'
            }).then((result) => {
              if (result.value) {
                accionAjaxPedido(id, 'recepcionar', 'recepcionado');
              }
            })
        });

        function accionAjaxPedido(id, accion, msj_exito) {
             $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: {
                    'action': accion,
                    'id': id
                },
                dataType: 'json',
            }).done(function (data) {
                Swal.fire(
                  'Enviado!',
                  'Tu pedido ha sido ' + msj_exito,
                  'success'
                );
                $('#myTableList').DataTable().ajax.reload();
            }).fail(function (jqXHR, textStatus, errorThrown) {
                //alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {

            });
        }

    });
    </script>

{% endblock js_page %}

templates/abastecimiento/pedido_view_det.html
{% extends 'base/base_backend.html' %}
{% load i18n %}
{% load static %}
{% load socialaccount %}
{% load widget_tweaks %}

{% block title %}
    {{ title_page }}
{% endblock title %}

{% block links_css_by_page %}
{% endblock %}

{% block links_js_by_page %}
{% endblock %}

{% block body %}
        <!-- Page Heading -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between"></div>
        <h1 class="h3 mb-2 text-gray-800">{{ main_title_content }}</h1>
        <div class="card shadow mb-4">
            <form id="formulario" method="post" enctype="multipart/form-data">
                <div class="card-header">
                    <h2>{{ subtitle_table }}</h2>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="id_numero">Numero</label>
                                {{ form.numero }}
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="id_tipo_documento">Tipo Doc.</label>
                                {{ form.tipo_documento }}
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="id_fecha">Fecha</label>
                                {{ form.fecha }}
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="id_tipo_pago">Forma pago</label>
                                {{ form.tipo_pago }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="id_proveedor">Proveedor</label>
                                {{ form.proveedor }}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="form-group table-responsive">
                            <table class="table table-bordered tableSpin" id="table_items">
                                <thead>
                                <tr class="">
                                    <th width="5%" class="table-bordered text-center">#</th>
                                    <th width="40%" class="table-bordered text-center">Producto</th>
                                    <th width="10%" class="table-bordered text-center">Cantidad</th>
                                    <th width="10%" class="table-bordered text-center">Precio</th>
                                    <th width="15%" class="table-bordered text-center">SUBTOTAL</th>
                                </tr>
                                </thead>
                                <tbody id="tbody-seleccionados">
                                    {% for detalle in pedido.detalles.all %}
                                    <tr id="fila-{{ forloop.counter }}">
                                        <td>{{ forloop.counter }}</td>
                                        <td>
                                            <div class="form-group">
                                                <input type="text" class="form-control" id="producto_name-{{ detalle.pk }}" value="{{ detalle.producto.codigo }} | {{ detalle.producto.Nombre }}" disabled>
                                                <input type="hidden" id="producto_id-{{ detalle.pk }}" name="producto[]" value="{{ detalle.producto.pk }}">
                                                <input type="hidden" id="producto_id-__prefix__" name="detalle_id[]" value="{{ detalle.pk }}">
                                            </div>
                                        </td>
                                        <td>
                                            <div class="form-group">
                                                <input type="text" class="form-control text-right" id="cantidad-{{ detalle.pk }}" name="cantidad[]" value="{{ detalle.cantidad }}" disabled>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="form-group">
                                                <input type="text" class="form-control text-right" id="precio-{{ detalle.pk }}" name="precio[]" value="{{ detalle.precio }}" disabled>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="form-group">
                                                <input type="text" class="form-control text-right" id="subtotal-{{ detalle.pk }}" name="subtotal[]" value="{{ detalle.total }}" disabled>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                <input type="hidden" id="id_total_items" name="total_items" value="0">
                                <div id="items_eliminados"></div>
                            </table>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="id_total" class="offset-8 col-sm-2 col-form-label">Total</label>
                        <div class="col-sm-2">
                            {{ form.total }}
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <input action="action" class="btn btn-outline-secondary float-left" type="button" value="Regresar"
                           onclick="history.go(-1);"/>
                </div>
            </form>
        </div>

{% endblock %}

{% block js_page %}
    <script>


    </script>

{% endblock js_page %}