apps/producto/urls.py
from django.urls import path

from . import views
from .views import (
    CategoriaDelete,
    CategoriaEditar,
    CategoriaNew,
    CategoriaView,
    MarcaDelete,
    MarcaEditar,
    MarcaNew,
    MarcaView,
    ProductoDelete,
    ProductoEditar,
    ProductoNew,
    ProductoView,
    TipoProductoDelete,
    TipoProductoEditar,
    TipoProductoNew,
    TipoProductoView,
    delete_cart_shopping,
    deletetodocarrito,
    deletetodoCategoria,
    deletetodoMarca,
    deletetodoProducto,
    deletetodoTipoProducto,
    update_carrito,
    ListCarritoView,
)

# Le asignamos un nombre a la app
app_name = "prod"

urlpatterns = [
    # Urls Marca
    path("marca/list", MarcaView.as_view(), name="marca_list"),
    path("marca/new", MarcaNew.as_view(), name="marca_new"),
    path("marca/edit/<int:pk>", MarcaEditar.as_view(), name="marca_edit"),
    path("marca/Delete/<int:pk>", MarcaDelete.as_view(), name="marca_Delete"),
    path("deleallmarca", deletetodoMarca.as_view(), name="deletetodomarca"),
    # Urls Categorias
    path("categorias/list", CategoriaView.as_view(), name="categoria_list"),
    path("categorias/new", CategoriaNew.as_view(), name="categoria_new"),
    path("categorias/edit/<int:pk>", CategoriaEditar.as_view(), name="categoria_edit"),
    path("categorias/Delete/<int:pk>", CategoriaDelete.as_view(), name="categoria_Delete"),
    path("deleteallcategoria", deletetodoCategoria.as_view(), name="deletetodocategoria"),
    # Urls Tipo de Producto
    path("TipoProducto/list", TipoProductoView.as_view(), name="tipoproducto_list"),
    path("TipoProducto/new", TipoProductoNew.as_view(), name="tipoproducto_new"),
    path("TipoProducto/edit/<int:pk>", TipoProductoEditar.as_view(),name="tipoproducto_edit",),
    path("TipoProducto/Delete/<int:pk>", TipoProductoDelete.as_view(), name="TipoProducto_delete", ),
    path("delealltipoproducto", deletetodoTipoProducto.as_view(), name="deletetodotipoproducto",
    ),
    # Urls Productos.
    path("Producto/list", ProductoView.as_view(), name="producto_list"),
    path("Producto/new", ProductoNew.as_view(), name="producto_new"),
    path("Producto/edit/<str:pk>", ProductoEditar.as_view(), name="Producto_edit"),
    path("Producto/Delete/<str:pk>", ProductoDelete.as_view(), name="Producto_delete"),
    path("Productodeletetodo", deletetodoProducto.as_view(), name="productodeletetodo"),
    # Urls Carrito
    path("update/<str:pk>/", update_carrito, name="updatecarrito"),
    path("añadircarrito/<str:idproducto>/", views.añadircarrito, name="carrito"),
    path("detallecarrito/<str:pk>/", ListCarritoView.as_view(), name="detallecarrito"),
    path("removercarrito/<str:pk>/", delete_cart_shopping, name="removercarrito"),
    path("deleteall/", deletetodocarrito.as_view(), name="deleteall"),
]

ferreteria/urls.py
from apps.users.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin    
from django.urls import include, path
from django.views.generic import TemplateView
from ferreteria.views import DetailViewProducto, ListaCategorias, ListarCategorias

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("apps.dashboard.urls")),
    path("home/abastecimiento/", include("apps.abastecimiento.urls")),

    path("accounts/", include("allauth.urls")),
    path("prod/", include("apps.producto.urls")),
    path("user/", include("apps.users.urls")),
    path("cmp/", include("apps.cmp.urls")),

    path("redireccion/", TemplateView.as_view(template_name="redireccion.html"), name="redirect"),

    path("", ListaCategorias.as_view(), name="inicio"),
    path("ListarCategoria/edit/<str:pk>", ListarCategorias.as_view(), name="Listar_categorias"),
    path("Detalleproducto/<str:pk>", DetailViewProducto.as_view(), name="Detalle_Producto"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/producto/models.py
from apps.bases.models import ClaseModelo
from apps.users.models import User

# from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
import json
import requests
 
# Creamos la clase categoria
class Categoria(ClaseModelo):
    Nombre = models.CharField(
        max_length=50, help_text="Nombre de la categoria", unique=True
    )

    def __str__(self):
        return "{}".format(self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"


class TipoProducto(ClaseModelo):
    UNIT_CHOICES = (
        ("Kgs", "Kilogramos"),
        ("Lts", "Litros"),
        ("Un", "Unidades"),
    )
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    Nombre = models.CharField(max_length=50, help_text="Nombre de la categoria")
    Um = models.CharField("unidad de medida", max_length=15, choices=UNIT_CHOICES,)

    def __str__(self):
        return "{}:{}".format(self.categoria.Nombre, self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(TipoProducto, self).save()

    class Meta:
        verbose_name_plural = "Tipos de Productos"
        unique_together = ("categoria", "Nombre")


class Marca(ClaseModelo):
    """
    Marca de un Producto 
    """

    nombre = models.CharField("Nombre", max_length=30, default="Marca")

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"

    def __str__(self):
        return self.nombre


class Producto(ClaseModelo):
    Nombre = models.CharField(max_length=40, blank=False, help_text="Nombre de producto" )
    codigo = models.CharField(primary_key=True, max_length=18)
    precio = models.FloatField(default=0)
    descripcion = models.CharField(max_length=100, help_text="Descripcion de productos", default="descripcion")
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    color = models.CharField(max_length=20, help_text="Color del producto", null=True, blank=True)
    stock = models.IntegerField()
    id_proveedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                     limit_choices_to={"cargo": "Proveedor"}, )
    imagen = models.ImageField(upload_to="ferreteria",  null=True, blank=True)
    Categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    TipoProducto = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def actualizarStock(self, cantidad):
        # 10 => compro 5 ==> enviar (-5)
        # x = 10 + (-5) => 5
        if cantidad:
            try:
                self.stock += int(cantidad)
                self.save()
            except Exception as e:
                print("Error : {}".format(str(e)))

    def limit_stock(self):
        item=self.stock
        item=int(item)
        if (item <= 25):
            return 1
        if (item <= 60):
            return 2
        if (item >= 61 ):   
            return 3


class Carrito(models.Model):

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    ESTATUS = [
        ("open", "Abierto"),
        ("pagado", "Pagado"),
        ("pendiente", "Pendiente"),
    ]
    estatus = models.CharField(max_length=59, choices=ESTATUS, default="open",)
    monto_total = models.FloatField('Monto total', default=0)

    def get_total(self):
        total = 0
        for carrito_producto in self.detalles.all():
            total += carrito_producto.producto.precio * carrito_producto.cantidad
        return total

    def __str__(self):
        return "{}".format(self.id)


class CarritoProducto(models.Model):
    carrito = models.ForeignKey(
        Carrito, on_delete=models.CASCADE, related_name="detalles"
    )
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)

    def get_precio_parcial(self):
        return self.cantidad * self.producto.precio

    def __str__(self):
        return "{}".format(self.id)

apps/producto/forms.py
from django import forms

# Importamos el modelo al cual queremos acceder.
from .models import Categoria, Marca, Producto, TipoProducto, Carrito
# Realizamos el formularios de las categorias ...
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ["Nombre"]  # Que quieres que se muestre
        labels = {"nombre": "Nombre de la categoria"}
        widget = {"Nombre": forms.TextInput}  # Darle estilo

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
    
    #Validacion del Nombre
    # def clean_Nombre(self):
    #     Nombre= self.cleaned_data['Nombre']
    #     if not Nombre.isalpha():
    #         print('Nombre',Nombre)
    #         raise forms.ValidationError("No se puede ingresar un tipo de valor Numerico")
    #     return Nombre


# Definimos El forms De tipo de Producto
class TipoProductoForm(forms.ModelForm):
    class Meta:
        model = TipoProducto
        fields = ["categoria", "Nombre", "Um"]
        labels = {"nombre": "Nombre de producto"}
        widget = {"Nombre": forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
        self.fields["categoria"].empty_label = "Seleccione Categoria"
        self.fields["Nombre"].widget.attrs.update(
            {"placeholder": " Nombre del tipo de Producto"}
        )
        self.fields["Um"].widget.attrs.update(
            {"placeholder": " Ingrese Unidad de medida"}
        )

    #Validacion de categoria
    def clean_categoria(self):
        categoria =self.cleaned_data['categoria']
        if categoria == '':
            raise forms.ValidationError("No puede estar el campo Vacio")
        return categoria

    # def clean_Nombre(self):
    #     Nombre =self.cleaned_data['Nombre']
    #     if not Nombre.isalpha():
    #         print('Nombre',Nombre)
    #         raise forms.ValidationError("No se puede ingresar un tipo de valor Numerico")
    #     return Nombre
#Validamos el tipo de producto



# Definimos El forms de producto


class ProductoForms(forms.ModelForm):
    class Meta:
        model = Producto  # Seleccionamos el producto en el cual queremos acceder
        fields = [
            "Nombre",
            "codigo",
            "precio",
            "descripcion",
            "marca",
            "color",
            "stock",
            "id_proveedor",
            "imagen",
            "Categoria",
            "TipoProducto",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
            self.fields["Nombre"].widget.attrs.update(
                {"placeholder": " Nombre del Producto"}
            )
            self.fields["codigo"].widget.attrs.update(
                {"placeholder": " Ingrese codigo"}
            )
            self.fields["stock"].widget.attrs.update({"placeholder": " Stock"})
            self.fields["descripcion"].widget.attrs.update(
                {"placeholder": " Descripcion"}
            )
            self.fields["color"].widget.attrs.update({"placeholder": "Ingrese color"})
            self.fields["imagen"].widget.attrs.update({"id": "ImagenTxt"})

# #Validacion de codigo
#     def clean_codigo(self):
#             codigo =self.cleaned_data['codigo']
#             if codigo <= 0:
#                 raise forms.ValidationError("No puede ingresar un valor igual o inferior a 0")
#                 return codigo
#             else:
#                 return codigo
      
#Validacion del stock
    def clean_stock(self):
        stock =self.cleaned_data['stock']
        if stock <= 0:
            raise forms.ValidationError("No puede ingresar un valor igual o inferior a 0")
            return stock
        else:
            return stock

#Validacion del precio
    def clean_precio(self):
        precio =self.cleaned_data['precio']
        if precio <= 0 or precio == "":
            raise forms.ValidationError("No puede ingresar un valor igual o inferior a 0")
            return precio
        else:
            return precio

#Validacion de Nombre 
    # def clean_Nombre(self):
    #     Nombre =self.cleaned_data['Nombre']
    #     if not Nombre.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un dato de valor Numerico")
    #     return Nombre

#Validacion de color
    # def clean_color(self):
    #     color=self.cleaned_data['color']
    #     if not color.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un dato de valor Numerico")
    #     return color
    
#Validacion de descripcion
    # def clean_descripcion(self):
    #     descripcion=self.cleaned_data['descripcion']
    #     if not descripcion.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un dato de valor Numerico")
    #     return descripcion


# Realizamos el formulario de Marca
class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ["nombre"]  # Que quieres que se muestre
        labels = {"nombre": "Nombre de la Marca"}
        widget = {"nombre": forms.TextInput}  # Darle estilo

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})
            
    # def clean_nombre(self):
    #     nombre= self.cleaned_data['nombre']
    #     if not nombre.isalpha():
    #         raise forms.ValidationError("No se puede ingresar un tipo de valor Numerico")
    #     return nombre
    
    




class CarritoPagarForm(forms.ModelForm):

    sede_desc = forms.CharField(widget=forms.TextInput(), required=False)

    class Meta:
        model = Carrito
        exclude = ['usuario', 'estatus', 'monto_total']

templates/producto/producto_delete.html
{% extends 'base/base.html' %}

{% block title %}
Eliminar Producto
{% endblock title %}


{% block llenar %}
<form class="p-4" role="form" method="POST" class="form-inline">
  {% csrf_token %}
  <div class="card border-left-danger shadow h-100 py-2">
    <div class="card-header text-dark font-weight-bold" style="font-size: 30px;">¿Eliminar el producto {{ product.Nombre }} ? </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <button type="submit" class="btn btn-danger">  <i class="far fa-question-circle"></i>Si, eliminar</button>
            <a href="{% url 'prod:producto_list' %}" class="btn btn-success "><span class="fa fa-undo"></span>Cancelar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock llenar %}

templates/producto/producto_edit.html
{% extends 'base/base.html' %}


{% block llenar %}

<form class="p-4" role="form" method="POST" class="form-inline" enctype="multipart/form-data">{% csrf_token %}
    {% include 'base/partial/erroreditar.html' %}
    <div class="card border-left-warning shadow h-100 py-2">
        <div class="card-header" style="font-size: 30px;">Editar producto</div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Nombre</label>
                        {{ form.Nombre }}
                        {% if form.Nombre.errors %}
                        {% for error in form.Nombre.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Código</label>
                        {{ form.codigo }}
                        {% if form.codigo.errors %}
                        {% for error in form.codigo.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Categoría</label>
                        {{ form.Categoria}}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Tipo de producto</label>
                        {{ form.TipoProducto }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Proveedor</label>
                        {{ form.id_proveedor }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Precio</label>
                        {{ form.precio}}
                        {% if form.precio.errors %}
                        {% for error in form.precio.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Stock</label>
                        {{ form.stock }}
                        {% if form.stock.errors %}
                        {% for error in form.stock.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Color</label>
                        {{ form.color }}
                        {% if form.color.errors %}
                        {% for error in form.color.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Descripción</label>
                        {{ form.descripcion }}
                        {% if form.descripcion.errors %}
                        {% for error in form.descripcion.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                        
                            
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Marca</label>
                        {{ form.marca }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold">Imagen</label>
                        {{ form.imagen }}
                    </div>
                </div>
            </div>
            <div class="row"></div>
                <div class="col-md-3">
                    <div class="form-group">
                        <button type="submit" class="btn btn-warning mt-3 mr-1  "><span
                            class="fa fa-save"></span>Editar</button>
                          <a href="{% url 'prod:producto_list' %}" class="btn btn-danger mt-3 "><span
                            class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% block js_page %}
{% include 'base/partial/script.html' %}
{% endblock js_page %}
{% endblock llenar %}

templates/producto/producto_form.html
{% extends 'base/base.html' %}


{% block llenar %}
<form class="p-4" role="form" method="POST" class="form-inline" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'base/partial/error.html' %}
    <div class="card border-left-success shadow h-100 py-2">
        <div class="card-header" style="font-size: 30px;">Nuevo producto</div>
        <div class="card-body ">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_nombre">Nombre</label>
                        {{ form.Nombre }}
                        {% if form.Nombre.errors %}
                        {% for error in form.Nombre.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_codigo">Código</label>
                        {{ form.codigo }}
                        {% if form.codigo.errors %}
                        {% for error in form.codigo.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_categoria">Categoría</label>
                        {{ form.Categoria }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_tipoproducto">Tipo de producto</label>
                        {{ form.TipoProducto }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_proveedor">Proveedor</label>
                        {{ form.id_proveedor }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_precio">Precio</label>
                        {{ form.precio }}
                        {% if form.precio.errors %}
                        {% for error in form.precio.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_imagen">Imagen</label>
                        {{form.imagen}}
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_stock">Stock</label>
                        {{ form.stock }}
                        {% if form.stock.errors %}
                        {% for error in form.stock.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_marca">Marca</label>
                        {{ form.marca }}
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_color">Color</label>
                        {{ form.color }}
                        {% if form.color.errors %}
                        {% for error in form.color.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                            
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="text-dark font-weight-bold" for="id_descripcion">Descripción</label>
                        {{form.descripcion}}
                        {% if form.descripcion.errors %}
                        {% for error in form.descripcion.errors %}
                        <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-4 " style="margin-top: 30px;">
                    <div class="form-group">
                        <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>Guardar</button>
                        <a href="{% url 'prod:producto_list' %}" class="btn btn-danger "><span
                                class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>

</form>

{% block js_page %}
{% include 'base/partial/script.html' %}
<script>
    
</script>
{% endblock js_page %}
{% endblock llenar %}

templates/producto/producto_list.html
{% extends 'base/base.html' %}

{% block title %}
Lista
{% endblock title %}


{% block llenar %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between"></div>
    <h1 class="h3 mb-2 text-gray-800">Listado de productos</h1>
    
    {% for item in product  %} 
        {% if item.limit_stock == 1   %}
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close " data-dismiss="alert">×</button>
           <h6 class="text-strong">PRODUCTO: {{ item.Nombre}} ESTA CON STOCK CRITICO</h6>  
        </div>
        {% else %}
        <div class="alert alert-success d-none" role="alert">
            {{item.stock}} 
          </div>
        {% endif %}
            
    
    {% endfor %}    
    <div class="row">
        <div class="col-4">
            <a class="btn btn-primary" href="{% url 'prod:producto_new' %}"><i class="far fa-calendar-plus"></i> Nuevo producto</a>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            {% if not product %}
            <div class="alert alert-info"> No hay productos que mostrar</div>
            {% else %}
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="15">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Nombre</th>
                            <th>Tipo_Producto</th>
                            <th>Id_proveedor</th>
                            <th>Stock</th>
                            <th>Precio</th>
                            <th>Descripción</th>
                            <th>Marca</th>
                            <th>Color</th>
                            <th>Fecha_Modificada</th>
                            <th class="all">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in product %}
                        <tr>
                            <td>{{ item.codigo }}</td>
                            <td>{{ item.Nombre }}</td>
                            <td>{{ item.TipoProducto }}</td>
                            <td>{{ item.id_proveedor }}</td>
                            <td class="
                            {% if item.limit_stock == 1 %} text-danger {% endif %}
                            {% if item.limit_stock == 2 %} text-warning {% endif %} 
                            {% if item.limit_stock == 3 %} text-success {% endif %} " 
                            >{{ item.stock }}</td>
                            <td>{{ item.precio }}</td>
                            <td>{{ item.descripcion }}</td>
                            <td>{{ item.marca }}</td>
                            <td>{{ item.color}}</td>
                            <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                            <td>
                                <a href="{% url 'prod:Producto_edit' item.pk %}" class="btn btn-warning btn-circle"
                                    role="button"><i class="far fa-edit"></i></a>
                                <a href="{% url 'prod:Producto_delete' item.pk %}" class="btn btn-warning btn-danger"
                                    role="button"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="col-4 container" >
                    <form  action="{% url 'prod:productodeletetodo' %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            <i class="far fa-trash-alt"></i>
                            <span>Limpiar todo</span>
                        </button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

</div>
{% endblock llenar %}

{% block js_page %}
       

{% endblock js_page %}