apps/producto/urls.py
from django.urls import path

from . import views
from .views import (
    CategoriaDelete,
    CategoriaEditar,
    CategoriaNew,
    CategoriaView,
    MarcaDelete,
    MarcaEditar,
    MarcaNew,
    MarcaView,
    ProductoDelete,
    ProductoEditar,
    ProductoNew,
    ProductoView,
    TipoProductoDelete,
    TipoProductoEditar,
    TipoProductoNew,
    TipoProductoView,
    delete_cart_shopping,
    deletetodocarrito,
    deletetodoCategoria,
    deletetodoMarca,
    deletetodoProducto,
    deletetodoTipoProducto,
    update_carrito,
    ListCarritoView,
)

# Le asignamos un nombre a la app
app_name = "prod"

urlpatterns = [
    # Urls Marca
    path("marca/list", MarcaView.as_view(), name="marca_list"),
    path("marca/new", MarcaNew.as_view(), name="marca_new"),
    path("marca/edit/<int:pk>", MarcaEditar.as_view(), name="marca_edit"),
    path("marca/Delete/<int:pk>", MarcaDelete.as_view(), name="marca_Delete"),
    path("deleallmarca", deletetodoMarca.as_view(), name="deletetodomarca"),
    # Urls Categorias
    path("categorias/list", CategoriaView.as_view(), name="categoria_list"),
    path("categorias/new", CategoriaNew.as_view(), name="categoria_new"),
    path("categorias/edit/<int:pk>", CategoriaEditar.as_view(), name="categoria_edit"),
    path("categorias/Delete/<int:pk>", CategoriaDelete.as_view(), name="categoria_Delete"),
    path("deleteallcategoria", deletetodoCategoria.as_view(), name="deletetodocategoria"),
    # Urls Tipo de Producto
    path("TipoProducto/list", TipoProductoView.as_view(), name="tipoproducto_list"),
    path("TipoProducto/new", TipoProductoNew.as_view(), name="tipoproducto_new"),
    path("TipoProducto/edit/<int:pk>", TipoProductoEditar.as_view(),name="tipoproducto_edit",),
    path("TipoProducto/Delete/<int:pk>", TipoProductoDelete.as_view(), name="TipoProducto_delete", ),
    path("delealltipoproducto", deletetodoTipoProducto.as_view(), name="deletetodotipoproducto",
    ),
    # Urls Productos.
    path("Producto/list", ProductoView.as_view(), name="producto_list"),
    path("Producto/new", ProductoNew.as_view(), name="producto_new"),
    path("Producto/edit/<str:pk>", ProductoEditar.as_view(), name="Producto_edit"),
    path("Producto/Delete/<str:pk>", ProductoDelete.as_view(), name="Producto_delete"),
    path("Productodeletetodo", deletetodoProducto.as_view(), name="productodeletetodo"),
    # Urls Carrito
    path("update/<str:pk>/", update_carrito, name="updatecarrito"),
    path("añadircarrito/<str:idproducto>/", views.añadircarrito, name="carrito"),
    path("detallecarrito/<str:pk>/", ListCarritoView.as_view(), name="detallecarrito"),
    path("removercarrito/<str:pk>/", delete_cart_shopping, name="removercarrito"),
    path("deleteall/", deletetodocarrito.as_view(), name="deleteall"),
]

ferreteria/urls.py
from apps.users.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin    
from django.urls import include, path
from django.views.generic import TemplateView
from ferreteria.views import DetailViewProducto, ListaCategorias, ListarCategorias

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("apps.dashboard.urls")),
    path("home/abastecimiento/", include("apps.abastecimiento.urls")),

    path("accounts/", include("allauth.urls")),
    path("prod/", include("apps.producto.urls")),
    path("user/", include("apps.users.urls")),
    path("cmp/", include("apps.cmp.urls")),

    path("redireccion/", TemplateView.as_view(template_name="redireccion.html"), name="redirect"),

    path("", ListaCategorias.as_view(), name="inicio"),
    path("ListarCategoria/edit/<str:pk>", ListarCategorias.as_view(), name="Listar_categorias"),
    path("Detalleproducto/<str:pk>", DetailViewProducto.as_view(), name="Detalle_Producto"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/producto/models.py
from apps.bases.models import ClaseModelo
from apps.users.models import User

# from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
import json
import requests
 
# Creamos la clase categoria
class Categoria(ClaseModelo):
    Nombre = models.CharField(
        max_length=50, help_text="Nombre de la categoria", unique=True
    )

    def __str__(self):
        return "{}".format(self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"


class TipoProducto(ClaseModelo):
    UNIT_CHOICES = (
        ("Kgs", "Kilogramos"),
        ("Lts", "Litros"),
        ("Un", "Unidades"),
    )
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    Nombre = models.CharField(max_length=50, help_text="Nombre de la categoria")
    Um = models.CharField("unidad de medida", max_length=15, choices=UNIT_CHOICES,)

    def __str__(self):
        return "{}:{}".format(self.categoria.Nombre, self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(TipoProducto, self).save()

    class Meta:
        verbose_name_plural = "Tipos de Productos"
        unique_together = ("categoria", "Nombre")


class Marca(ClaseModelo):
    """
    Marca de un Producto 
    """

    nombre = models.CharField("Nombre", max_length=30, default="Marca")

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"

    def __str__(self):
        return self.nombre


class Producto(ClaseModelo):
    Nombre = models.CharField(max_length=40, blank=False, help_text="Nombre de producto" )
    codigo = models.CharField(primary_key=True, max_length=18)
    precio = models.FloatField(default=0)
    descripcion = models.CharField(max_length=100, help_text="Descripcion de productos", default="descripcion")
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    color = models.CharField(max_length=20, help_text="Color del producto", null=True, blank=True)
    stock = models.IntegerField()
    id_proveedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                     limit_choices_to={"cargo": "Proveedor"}, )
    imagen = models.ImageField(upload_to="ferreteria",  null=True, blank=True)
    Categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    TipoProducto = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.Nombre)

    def save(self):
        self.Nombre = self.Nombre.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def actualizarStock(self, cantidad):
        # 10 => compro 5 ==> enviar (-5)
        # x = 10 + (-5) => 5
        if cantidad:
            try:
                self.stock += int(cantidad)
                self.save()
            except Exception as e:
                print("Error : {}".format(str(e)))

    def limit_stock(self):
        item=self.stock
        item=int(item)
        if (item <= 25):
            return 1
        if (item <= 60):
            return 2
        if (item >= 61 ):   
            return 3


class Carrito(models.Model):

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    ESTATUS = [
        ("open", "Abierto"),
        ("pagado", "Pagado"),
        ("pendiente", "Pendiente"),
    ]
    estatus = models.CharField(max_length=59, choices=ESTATUS, default="open",)
    monto_total = models.FloatField('Monto total', default=0)

    def get_total(self):
        total = 0
        for carrito_producto in self.detalles.all():
            total += carrito_producto.producto.precio * carrito_producto.cantidad
        return total

    def __str__(self):
        return "{}".format(self.id)


class CarritoProducto(models.Model):
    carrito = models.ForeignKey(
        Carrito, on_delete=models.CASCADE, related_name="detalles"
    )
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)

    def get_precio_parcial(self):
        return self.cantidad * self.producto.precio

    def __str__(self):
        return "{}".format(self.id)

templates/tipo_producto/tipo_productoForm.html
{% extends 'base/base.html' %}


{% block llenar %}
<form class="p-4" id="form" role="form" method="POST" class="form-inline">
    {% csrf_token %}
    {% include 'base/partial/error.html' %}
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-header" style="font-size: 30px;">Nuevo tipo de producto</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="text-dark font-weight-bold" for="id_categoria">Categoría</label>
                            {{ form.categoria }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="text-dark font-weight-bold" for="id_nombre">Nombre</label>
                            {{ form.Nombre }}
                            {% if form.Nombre.errors %}
                            {% for error in form.Nombre.errors %}
                            <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="text-dark font-weight-bold" for="id_unidadmedida">Unidad de Medida</label>
                            {{ form.Um }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success "><span
                                class="fa fa-save"></span>Guardar</button>
                                 <a href="{% url 'prod:tipoproducto_list' %}" class="btn btn-danger"><span
                                class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
</form>
{% block js_page %}
{% include 'base/partial/script.html' %}
{% endblock js_page %}
{% endblock llenar %}

templates/tipo_producto/tipo_productodelete.html
{% extends 'base/base.html' %}


{% block llenar %}
<form class="p-4" role="form" method="POST" class="form-inline">{% csrf_token %}
      <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-header text-dark font-weight-bold" style="font-size: 30px;">¿Eliminar el producto {{ obj.Nombre }} ? </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <div class="form-group">
                <button type="submit" class="btn btn-danger">  <i class="far fa-question-circle"></i>Si, eliminar</button>
                <a href="{% url 'prod:tipoproducto_list' %}" class="btn btn-success "><span class="fa fa-undo"></span>Cancelar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
</form>

{% endblock llenar %}

templates/tipo_producto/tipo_productolist.html
{% extends 'base/base.html' %}

{% block title %}
Tipo Producto
{% endblock title %}


{% block llenar %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Listado de Tipos de Producto</h1>
    <div class="row">
        <div class="col-4">
            <a class="btn btn-primary" href="{% url 'prod:tipoproducto_new' %}"><i class="fas fa-plus"></i>Nuevo Tipo de Producto</a>
        </div>
 
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            {% if not obj %}
            <div class="alert alert-info"> No hay Tipos de Producto que mostrar</div>
            {% else %}
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Categoría</th>
                            <th>Nombre</th>
                            <th>Fecha de creación</th>
                            <th>Fecha de modificación</th>
                            <th>Unidad de Medida</th>
                            <th class="all">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %} 
                        <tr>
                            <td>{{ item.categoria }}</td>
                            <td>{{ item.Nombre }}</td>
                            <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                            <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                            <td>{{ item.Um }}</td>
                            <td>
                                <a href="{% url 'prod:tipoproducto_edit' item.id %}" class="btn btn-warning btn-circle"
                                    role="button"><i class="far fa-edit"></i></a>
                                <a href="{% url 'prod:TipoProducto_delete' item.id %}" class="btn btn-warning btn-danger"
                                    role="button"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="col-4 container" >
                    <form  action="{% url 'prod:deletetodotipoproducto' %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            <i class="far fa-trash-alt"></i>
                            <span>Limpiar todo</span>
                        </button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock llenar %}

templates/tipo_producto/tipoproducto_edit.html
{% extends 'base/base.html' %}


{% block llenar %}

<form class="p-4" role="form" method="POST" class="form-inline">{% csrf_token %}
  {% include 'base/partial/erroreditar.html' %}
  <div class="card border-left-warning shadow h-100 py-2">
    <div class="card-header" style="font-size: 30px;">Editar tipo de producto</div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label class="text-dark font-weight-bold"> Categoría</label>
            {{ form.categoria}}
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label class="text-dark font-weight-bold">Nombre</label>
            {{ form.Nombre}}
            {% if form.Nombre.errors %}
            {% for error in form.Nombre.errors %}
            <span class="font-bold col-red text-danger" style="font-size: 12px;">{{ error|escape }}</span>
            {% endfor %}
            {% endif %}
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label class="text-dark font-weight-bold">Unidad de Medida</label>
            {{ form.Um}}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <button type="submit" class="btn btn-warning mt-3 mr-1 "><span class="fa fa-save"></span>Editar</button>
            <a href="{% url 'prod:tipoproducto_list' %}" class="btn btn-danger mt-3 "><span class="fa fa-undo"></span>Cancelar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% block js_page %}
{% include 'base/partial/script.html' %}
{% endblock js_page %}
{% endblock llenar %}